backend:
  name: github
  repo: ps-aux/simplest-spa

media_folder: assets
public_folder: assets

collections:
  - name: team-member
    identifier_field: id
    label: Team member
    folder: data/team
    create: true
    format: json
    fields:
      - { name: id, label: Id }
      - { name: name, label: Name, widget: string }
      - { name: photos, label: Photos, widget: list, field: { label: photo, widget: file} }